### ISSUE TITLE
you can get frozen when respawning (related to button mashing?)

### ISSUE THREAD

**Issue by garzaa** [adriangarza/vaporvania#96]

**Comment by garzaa** [comment]
looks like it's related to jumping in the middle of the respawn animation

**Comment by adriangarza** [comment]
but also only when there's an active respawn point, you can't replicate it when the game has just started

**Comment by adriangarza** [comment]
the "dead" boolean is getting set to false too early

**Comment by garzaa** [comment]
it's not just jumping. spamming a single button doesn't do it. might be a keymash thing

**Comment by garzaa** [comment]
it's also really REALLY hard to replicate

**Comment by garzaa** [comment]
from stacktracing, the last time the player is unfrozen when the glitch happens is in `Die` where `Unfreeze` is called in `InterruptAttack`. maybe take that out and see if it fixes it.

**Comment by garzaa** [comment]
i am the world's greatest
